:cursing_face:	mac

diff --git a/.github/workflows/multiarch-build-deploy.yaml b/.github/workflows/multiarch-build-deploy.yaml
--- a/.github/workflows/multiarch-build-deploy.yaml
+++ b/.github/workflows/multiarch-build-deploy.yaml
@@ -26,7 +26,12 @@ jobs:
 
       - name: Install Docker
         if: matrix.os == 'macos-latest'
-        run: brew install docker colima
+        run: |
+          HOMEBREW_NO_AUTO_UPDATE=1 brew install --cask docker \
+          sudo /Applications/Docker.app/Contents/MacOS/Docker --unattended --install-privileged-components \
+          open -a /Applications/Docker.app --args --unattended --accept-license \
+          echo "We are waiting for Docker to be up and running. It can take over 2 minutes..." \
+          while ! /Applications/Docker.app/Contents/Resources/bin/docker info &>/dev/null; do sleep 1; done
 
       - name: Login to DockerHub
         uses: docker/login-action@v2
